title: Jiawei Pei's Homepage
page-top-title: Jiawei Pei
top-section-bg-text: Computer Science
home-subtitle: Jiawei Pei&ensp;|&ensp;裴嘉伟
copyright-text: '&copy; Jiawei Pei 2023-2025. All Rights Reserved.'
